{% set name = "watchdog-gevent" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchdog_gevent-{{ version }}.tar.gz
  sha256: ae6b94d0f8c8ce1c5956cd865f612b61f456cf19801744bba25a349fe8e8c337

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - gevent >=1.1
    - python >=3.6
    - watchdog >=0.8

test:
  imports:
    - watchdog_gevent

about:
  home: https://github.com/Bogdanp/watchdog_gevent
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A gevent-based observer for watchdog.
  dev_url: https://github.com/Bogdanp/watchdog_gevent

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus
