{% set name = "watchdog-gevent" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchdog_gevent-{{ version }}.tar.gz
  sha256: beb63c4484b93301dd3a2383a072a7598269b88ab84df17fc58ca487eda5deff

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - gevent >=1.1
    - python >=3.6
    - watchdog >=0.8

test:
  imports:
    - watchdog_gevent

about:
  home: https://github.com/Bogdanp/watchdog_gevent
  license: APACHE-2.0
  license_family: Apache-2.0
  license_file: LICENSE
  summary: A gevent-based observer for watchdog.
  dev_url: https://github.com/Bogdanp/watchdog_gevent

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus
