travis:
  secure:
    BINSTAR_TOKEN: fyLfq6DgKcQ0Hirsx3JdZ2LeG+F82UB0xCKRrw8UIO81L5QA/zojYO87Ky2FvR2dWO6s99GispgGbrTvTO5uElhhZU9xtpVFhu8BFVMSZyQsCjQxYMkSHgje9uHAw8tcznuWvYlxpTuorqTCQghmERH9I6lt85eACI+keWOg71wmgr+0310ajyDYN1mA4l/t4DH9o2eij/3mdDuI8CnqwGzpz2uYUBrv+Yu6H4DPEpuQ3aB5SVAd4AU+Mo+0PEN7ZVOk1smp+LYW48Dxc1eqcqzwGb5wPK3rOJyXFCSpYVi2RFdwkgxhTa1HR59SBAiko7iWPiOSiNRAKTa/+Y8flMA/TRHtLummbbgEj1A2IFcdBFbcSyTaJEAZOQcSnMrnYQVB/puUjAgLhaSq1ZiTK6nHR/IXPrHdJSBgwISf4agmXF/pEqvl2WRP8d79V0VYUKT+VEb3Tl+bG+zWn7WQUnzks5nIGWITyBXeCjdh1r78dmAy8qCi3XUq1/z83Y5Dw7NtiKSNszkCSXL+5cAwrt2xnOHKni+C8r3Y+1ui2wj+PIeK3pD7kK4WYXj+3eC8YrJzdn9ry2N/Fj00yhzvEfSiO+umUZRRTNqyECTef2DAULHtEhT2Dk4ZhItavpPKmLiqW8WP5QmGqdkWtkXgHUi1qLA0K4XZAw0mo3JapGI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
